
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    locations: classpath:db/migration,classpath:com/ecommerce/filterprices/infrastructure/adapter/db/migration

logging:
  level:
    root: INFO

file:
  csv:
    price: price.csv
