
CREATE TABLE price (id INTEGER NOT NULL,brand_id INTEGER NOT NULL, start_date DATETIME, end_date DATETIME, INTEGER PRICE_LIST, INTEGER PRODUCT_ID, INTEGER PRIORITY, DOUBLE  price, String currency, PRIMARY KEY (id));



